// Importing the createSlice function from '@reduxjs/toolkit'
import { createSlice } from '@reduxjs/toolkit'

// Creating a slice of state called 'home' using createSlice
export const homeSlice = createSlice({
    // Name of the slice
    name: 'home',
    // Initial state for the slice
    initialState: {
        url: {},    // Initial value for the 'url' property
        genres: {}, // Initial value for the 'genres' property
    },
    // Reducer functions to handle state updates
    reducers: {
        // Reducer function to update 'url' property in the state
        getApiConfiguration: (state, action) => {
            state.url = action.payload; // Updating 'url' with the payload provided
        },
        // Reducer function to update 'genres' property in the state
        getGenres: (state, action) => {
            state.genres = action.payload; // Updating 'genres' with the payload provided
        }
    }
})

// Action creators are generated for each case reducer function
export const { getApiConfiguration, getGenres } = homeSlice.actions

// Exporting the reducer function generated by createSlice
export default homeSlice.reducer
